version: '3'

services:
     nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "8080:80"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
          - app
        networks:
          - node-network
     
     app:
        build: 
            context: node
        container_name: app
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
        tty: true    
        ports: 
            - "3000:3000"
        command: "npm run start"
        depends_on:
            - db

     db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
          - ./mysql:/var/lib/mysql
        environment: 
          - MYSQL_DATABASE=nodedb
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_user=root
        ports: 
            - "3306:3306"
        networks:
          - node-network
    
networks:
  node-network:
    driver: bridge
