version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - node-network

  app:
    build:
      context: ./node  # Verifique o caminho correto para o Dockerfile do Node.js
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app  # Verifique se este mapeamento está correto para o seu projeto Node.js
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

